<?xml version="1.0"?>
<robot name="caffeine" xmlns:xacro="http://www.ros.org/wiki/xacro">
	<xacro:include filename="$(find caffeine_description)/urdf/base.xacro"/>
	<xacro:include filename="$(find caffeine_description)/urdf/inertias.xacro"/>
	<xacro:include filename="$(find caffeine_description)/urdf/wheels.xacro"/>
	<xacro:include filename="$(find caffeine_description)/urdf/caffeine.gazebo.xacro"/>

	<link name="world">
	</link>

	<!-- Base link -->
	<link name="base_link">
		<xacro:base_link_description/>
	</link>
	<joint name="world_joint" type="fixed">
		<parent link="world"/>
		<child link="base_link"/>
		<origin xyz="0 0 -0.1"/>
	</joint>

	<!-- Right front wheel -->
	<link name="right_front_wheel">
		<xacro:wheel_link_description />
	</link>
	<joint name="right_front_wheel_joint" type="continuous">
		<parent link="base_link"/>
		<child link="right_front_wheel"/>
		<origin xyz="${length/3.0} ${-width/2.0 - wheel_base_offset} ${-height/2.5}" rpy="0 0 0"/>
		<axis xyz="0 1 0"/>
		<dynamics damping="${wheel_df}"/>
	</joint>
	<xacro:Transmission joint="right_front_wheel_joint"/>

	<!-- Right back wheel -->
	<link name="right_back_wheel">
		<xacro:wheel_link_description />
	</link>
	<joint name="right_back_wheel_joint" type="continuous">
		<parent link="base_link"/>
		<child link="right_back_wheel"/>
		<origin xyz="${-length/3.0} ${-width/2.0 - wheel_base_offset} ${-height/2.5}" rpy="0 0 0"/>
		<axis xyz="0 1 0"/>
		<dynamics damping="${wheel_df}"/>
	</joint>
	<xacro:Transmission joint="right_back_wheel_joint"/>

	<!-- Left front wheel -->
	<link name="left_front_wheel">
		<xacro:wheel_link_description/>
	</link>
	<joint name="left_front_wheel_joint" type="continuous">
		<parent link="base_link"/>
		<child link="left_front_wheel"/>
		<origin xyz="${length/3.0} ${width/2.0 + wheel_base_offset} ${-height/2.5}" rpy="0 0 0"/>
		<axis xyz="0 1 0"/>
		<dynamics damping="${wheel_df}"/>
	</joint>
	<xacro:Transmission joint="left_front_wheel_joint"/>

	<!-- Left back wheel -->
	<link name="left_back_wheel">
		<xacro:wheel_link_description/>
	</link>
	<joint name="left_back_wheel_joint" type="continuous">
		<parent link="base_link"/>
		<child link="left_back_wheel"/>
		<origin xyz="${-length/3.0} ${width/2.0 + wheel_base_offset} ${-height/2.5}" rpy="0 0 0"/>
		<axis xyz="0 1 0"/>
		<dynamics damping="${wheel_df}"/>
	</joint>
	<xacro:Transmission joint="left_back_wheel_joint"/>
	
</robot>
