<?xml version="1.0"?>
<robot name="wheels" xmlns:xacro="http://www.ros.org/wiki/xacro">

	<xacro:include filename="$(find caffeine_description)/urdf/inertias.xacro"/>
	<!-- Mathematical constants -->
	<xacro:property name = "pi" value = "3.1415926535"/>

	<!-- Wheel constants -->
	<xacro:property name = "wheel_diam" value = "0.1"/>
	<xacro:property name = "wheel_length" value = "0.1"/>
	<xacro:property name = "wheel_mass" value = "2.0"/>
	<xacro:property name = "wheel_base_offset" value="0.02"/>
	<xacro:property name = "wheel_df" value = "0.0"/>
	
	
	<xacro:macro name="wheel_link_description">
		<visual>
			<origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
			<geometry>
				<cylinder length="${wheel_length}" radius="${wheel_diam/2.0}"/>
			</geometry>
			<material name="black"/>
		</visual>
		<collision>
			<origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
			<geometry>
				<cylinder length="${wheel_length}" radius="${wheel_diam/2.0}"/>
			</geometry>
		</collision>
		<inertial>
			<mass value="${wheel_mass}"/>
			<xacro:cylinder_inertia mass="${wheel_mass}" length="${wheel_length}" radius="${wheel_diam/2.0}"/>
		</inertial>
	</xacro:macro>
	

	<!-- this is used wherever necessary for all joints -->	
	<xacro:macro name="Transmission" params="joint">
		<transmission name="trans_${joint}">
			<type>transmission_interface/SimpleTransmission</type>
			<joint name="${joint}">
				<hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
			</joint>
			<actuator name="${joint}_motor">
				<hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
				<mechanicalReduction>1</mechanicalReduction>
			</actuator>
		</transmission>
	</xacro:macro>

</robot>



