<?xml version="1.0"?>
<robot name="caffeine" xmlns:xacro="http://ros.org/wiki/xacro">
   <xacro:include filename="$(find caffeine_description)/urdf/inertias.xacro"/>
   <xacro:include filename="$(find caffeine_description)/urdf/caffeine.gazebo.xacro"/>
   <xacro:include filename="$(find caffeine_description)/urdf/constants.xacro"/>

   <!-- xacro macro definitions for wheels -->
   <xacro:macro name="wheel_link_description">
      <visual>
         <origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
         <geometry>
            <cylinder length="${wheel_length}" radius="${wheel_diam/2.0}"/>
         </geometry>
      </visual>
      <collision>
         <origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
         <geometry>
            <cylinder length="${wheel_length}" radius="${wheel_diam/2.0}"/>
         </geometry>
      </collision>
      <inertial>
        <mass value="${wheel_mass}"/>
        <xacro:cylinder_inertia mass="${wheel_mass}" length="${wheel_length}" radius="${wheel_diam/2}"/>
      </inertial>
   </xacro:macro>

   <!-- Wheel motor definitions -->
   <xacro:macro name="Transmission" params="joint">
      <transmission name="trans_${joint}">
         <type>transmission_interface/SimpleTransmission</type>
         <joint name="${joint}">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
         </joint>
         <actuator name="${joint}_motor">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
         </actuator>
      </transmission>
   </xacro:macro>

   <!-- Base link -->
   <link name="base_link">
      <visual>
         <origin rpy="0 0 0" xyz="0 0 0"/>
         <geometry>
            <box size="${base_length} ${base_width} ${base_height}"/>
         </geometry>
      </visual>
      <collision>
         <origin rpy="0 0 0" xyz="0 0 0"/>
         <geometry>
            <box size="${base_length} ${base_width} ${base_height}"/>
         </geometry>
      </collision>
      <inertial>
         <mass value="${base_mass}"/>
         <xacro:box_inertia mass="${base_mass}" length="${base_length}" width="${base_width}" height="${base_height}"/>
      </inertial>
   </link>

        <!-- Right front wheel -->
        <link name="right_front_wheel">
                <xacro:wheel_link_description />
        </link>
        <joint name="right_front_wheel_joint" type="continuous">
                <parent link="base_link"/>
                <child link="right_front_wheel"/>
                <origin xyz="${base_length/3.0} ${-base_width/2.0 - wheel_base_offset} ${-base_height/2.5}" rpy="0 0 0"/>
                <axis xyz="0 1 0"/>
        </joint>
        <xacro:Transmission joint="right_front_wheel_joint"/>

        <!-- Right back wheel -->
        <link name="right_back_wheel">
                <xacro:wheel_link_description />
        </link>
        <joint name="right_back_wheel_joint" type="continuous">
                <parent link="base_link"/>
                <child link="right_back_wheel"/>
                <origin xyz="${-base_length/3.0} ${-base_width/2.0 - wheel_base_offset} ${-base_height/2.5}" rpy="0 0 0"/>
                <axis xyz="0 1 0"/>
        </joint>
        <xacro:Transmission joint="right_back_wheel_joint"/>

        <!-- Left front wheel -->
        <link name="left_front_wheel">
                <xacro:wheel_link_description />
        </link>
        <joint name="left_front_wheel_joint" type="continuous">
                <parent link="base_link"/>
                <child link="left_front_wheel"/>
                <origin xyz="${base_length/3.0} ${base_width/2.0 + wheel_base_offset} ${-base_height/2.5}" rpy="0 0 0"/>
                <axis xyz="0 1 0"/>
        </joint>
        <xacro:Transmission joint="left_front_wheel_joint"/>

        <!-- Left back wheel -->
        <link name="left_back_wheel">
                <xacro:wheel_link_description />
        </link>
        <joint name="left_back_wheel_joint" type="continuous">
                <parent link="base_link"/>
                <child link="left_back_wheel"/>
                <origin xyz="${-base_length/3.0} ${base_width/2.0 + wheel_base_offset} ${-base_height/2.5}" rpy="0 0 0"/>
                <axis xyz="0 1 0"/>
        </joint>
        <xacro:Transmission joint="left_back_wheel_joint"/>
</robot>
